language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

services:

install: travis_retry composer install --no-interaction --prefer-dist

before_script:
    - sleep 1

script: vendor/bin/phpunit --verbose
